release:
  title-prefix: 'v'
  initial-version: '0.2.0'
  tag-prefix: 'v'
  commit-note-replacers:
    - replace-prefix: 'breaking: '
      new-prefix: ''
    - replace-prefix: 'feature: '
      new-prefix: ''
    - replace-prefix: 'change: '
      new-prefix: ''
    - replace-prefix: 'fix: '
      new-prefix: ''
    - replace-prefix: 'document: '
      new-prefix: ''
    - replace-prefix: 'dependency: '
      new-prefix: ''
branch:
  which_branch:
    runs-on: ubuntu-latest
    steps:
      # extract branch name
      - name: Extract branch name
        shell: bash
        run: echo "APP_VERSION=${{ env.MAJOR_MINOR_VERSION }}${{ github.run_number }}" >> $GITHUB_ENV
      # extract branch name on pull request
      - name: Print branch name
        if: github.event_name == 'pull_request'
        run: echo "APP_VERSION=${{ env.MAJOR_MINOR_VERSION }}${{ github.run_number }}" >> $GITHUB_ENV
      # print branch name
      - name: Get branch name
        run: echo 'The branch name is' $BRANCH_NAME
  version-branch-prefix: 'v'
  bump-version-commit-prefix: 'v'
  base-branch: 
    - uses: nelonoel/branch-name@v1
    # Use branch name for whatever purpose
    - run: echo ${BRANCH_NAME}
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: ğŸš€ Exciting New Features
      labels:
        - feature
    - title: ğŸš€ Exciting New Features
      labels:
        - feature
    - title: ğŸ“š Content Updates
      labels:
        - content
    - title: ğŸ› Bugs Fixed
      labels:
        - bug
    - title: âœ… Tests Added
      labels:
        - tests
    - title: ğŸ”§ Refactors Made
      labels:
        - refactor
    - title: âš™ï¸ Behind the Scenes
      labels:
        - '*'
bump:
  default: 'patch'
  major:
    labels:
      - 'major'
    commits:
      - 'breaking:'
  minor:
    labels:
      - 'feature'
      - 'minor'
    commits:
      - 'feature:'