release:
  title-prefix: 'v'
  initial-version: '0.2.0'
  tag-prefix: 'v'
  commit-note-replacers:
    - replace-prefix: 'breaking: '
      new-prefix: ''
    - replace-prefix: 'feature: '
      new-prefix: ''
    - replace-prefix: 'change: '
      new-prefix: ''
    - replace-prefix: 'fix: '
      new-prefix: ''
    - replace-prefix: 'document: '
      new-prefix: ''
    - replace-prefix: 'dependency: '
      new-prefix: ''
branch:
  version-branch-prefix: 'v'
  bump-version-commit-prefix: 'v'
  base-branch: ${{ github.event.pull_request.base.ref }}
changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: ğŸš€ Exciting New Features
      labels:
        - feature
    - title: ğŸš€ Exciting New Features
      labels:
        - feature
    - title: ğŸ“š Content Updates
      labels:
        - content
    - title: ğŸ› Bugs Fixed
      labels:
        - bug
    - title: âœ… Tests Added
      labels:
        - tests
    - title: ğŸ”§ Refactors Made
      labels:
        - refactor
    - title: âš™ï¸ Behind the Scenes
      labels:
        - '*'
bump:
  default: 'patch'
  major:
    labels:
      - 'major'
    commits:
      - 'breaking:'
  minor:
    labels:
      - 'feature'
      - 'minor'
    commits:
      - 'feature:'